/* SkyGuide Master Film & TV File
   Counties: SF (22), Contra Costa, Alameda, Marin, Santa Cruz, Sonoma, Napa, SLO
   Consolidated for dynamic proximity and UI image rendering.
*/

const landmarks_bayarea_film = [
  // --- SAN FRANCISCO (The Big 22) ---
  { name: "Mrs. Doubtfire House", media: "Mrs. Doubtfire", coords: { lat: 37.7939, lng: -122.4364 }, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Mrs._Doubtfire_house_San_Francisco.jpg/640px-Mrs._Doubtfire_house_San_Francisco.jpg", history: "The iconic Victorian where Daniel Hillard disguised himself as a nanny.", fun_fact: "The house address in the movie (2640 Steiner) is its real-world address." },
  { name: "The Painted Ladies", media: "Full House", coords: { lat: 37.7763, lng: -122.4328 }, image: "https://images.unsplash.com/photo-1541464914902-1c752044565c?auto=format&fit=crop&w=600&q=80", history: "Postcard Row, featured in the opening credits of 'Full House'.", fun_fact: "The actual Tanner house is 1709 Broderick St, but these are the 'credits' stars." },
  { name: "Palace of Fine Arts", media: "The Rock / Vertigo", coords: { lat: 37.8029, lng: -122.4484 }, image: "https://images.unsplash.com/photo-1505245208761-ba87355ad484?auto=format&fit=crop&w=600&q=80", history: "The location of Sean Connery's meeting with his daughter in 'The Rock'.", fun_fact: "It was originally built for the 1915 World's Fair out of temporary materials." },
  { name: "Lombard Street", media: "Ant-Man / Bullitt", coords: { lat: 37.8021, lng: -122.4187 }, image: "https://images.unsplash.com/photo-1526315570803-08709426f859?auto=format&fit=crop&w=600&q=80", history: "The 'Crookedest Street in the World', a staple of SF car chases.", fun_fact: "The speed limit is only 5 mph—making chases here look faster than they are!" },
  { name: "Alcatraz Island", media: "Escape from Alcatraz / The Rock", coords: { lat: 37.8270, lng: -122.4230 }, image: "https://images.unsplash.com/photo-1548625310-9195dfb82922?auto=format&fit=crop&w=600&q=80", history: "The world's most famous prison-turned-movie set.", fun_fact: "Filming 'The Rock' required the cast to stay in the cells for hours to maintain 'mood'." },
  { name: "Fort Point", media: "Vertigo / Dawn of the Planet of the Apes", coords: { lat: 37.8105, lng: -122.4769 }, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Fort_Point_San_Francisco_2013.jpg/640px-Fort_Point_San_Francisco_2013.jpg", history: "Under the Golden Gate Bridge, where Scottie saves Madeleine in 'Vertigo'.", fun_fact: "The bridge engineers built a special arch specifically to save this historic fort." },
  { name: "Chinatown Gate", media: "Big Trouble in Little China", coords: { lat: 37.7907, lng: -122.4056 }, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Dragon_Gate_San_Francisco.jpg/640px-Dragon_Gate_San_Francisco.jpg", history: "The entrance to Jack Burton's adventure in the cult classic.", fun_fact: "This is the only 'authentic' Chinatown gate in the US with stone guardians." },
  { name: "Coit Tower", media: "The Enforcer / San Andreas", coords: { lat: 37.8024, lng: -122.4058 }, image: "https://images.unsplash.com/photo-1610313045564-88484e569f65?auto=format&fit=crop&w=600&q=80", history: "A frequent 'Dirty Harry' backdrop atop Telegraph Hill.", fun_fact: "The murals inside are some of the most detailed Depression-era art in America." },
  { name: "City Hall", media: "Raiders of the Lost Ark", coords: { lat: 37.7793, lng: -122.4193 }, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/San_Francisco_City_Hall_at_night.jpg/640px-San_Francisco_City_Hall_at_night.jpg", history: "Doubled as the U.S. Capitol interior for Indiana Jones.", fun_fact: "The dome is the 5th largest in the world—taller than the one in D.C." },
  { name: "555 California", media: "The Towering Inferno", coords: { lat: 37.7922, lng: -122.4038 }, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/555_California_Street_2.jpg/640px-555_California_Street_2.jpg", history: "Represented the ill-fated 'Glass Tower' skyscraper.", fun_fact: "It was the tallest building in the city for nearly 50 years." },
  { name: "The Fairmont Hotel", media: "Shang-Chi / The Rock", coords: { lat: 37.7925, lng: -122.4103 }, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Fairmont_Hotel_SF.jpg/640px-Fairmont_Hotel_SF.jpg", history: "The site of the drafting of the UN Charter and many luxury film sets.", fun_fact: "The 'Tonga Room' inside is a world-famous Tiki bar with indoor rainstorms." },
  { name: "Mission Dolores Park", media: "Milk", coords: { lat: 37.7596, lng: -122.4269 }, image: "https://images.unsplash.com/photo-1598114400508-36070621379b?auto=format&fit=crop&w=600&q=80", history: "The gathering place for Harvey Milk's political revolution.", fun_fact: "The park offers the 'truest' view of the SF skyline used in many indie films." },
  { name: "Grace Cathedral", media: "Bullitt", coords: { lat: 37.7919, lng: -122.4128 }, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Grace_Cathedral_San_Francisco.jpg/640px-Grace_Cathedral_San_Francisco.jpg", history: "A gothic masterpiece on Nob Hill used in classic noir thrillers.", fun_fact: "The cathedral contains two labyrinths for walking meditation." },
  { name: "Ferry Building", media: "Hulk (2003)", coords: { lat: 37.7955, lng: -122.3937 }, image: "https://images.unsplash.com/photo-1534067783941-51c9c23eea3fd?auto=format&fit=crop&w=600&q=80", history: "Where Hulk fought off helicopters in the Ang Lee version.", fun_fact: "The clock tower stayed running through the 1906 earthquake." },
  { name: "Kezar Stadium", media: "Dirty Harry", coords: { lat: 37.7670, lng: -122.4556 }, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Kezar_Stadium_Aerial.jpg/640px-Kezar_Stadium_Aerial.jpg", history: "Clint Eastwood's famous 'Do I feel lucky?' scene was filmed nearby.", fun_fact: "It was the original home of the San Francisco 49ers." },
  { name: "Musée Mécanique", media: "The Princess Diaries", coords: { lat: 37.8095, lng: -122.4163 }, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Mus%C3%A9e_M%C3%A9canique_San_Francisco.jpg/640px-Mus%C3%A9e_M%C3%A9canique_San_Francisco.jpg", history: "The antique arcade where Princess Mia learns about her lineage.", fun_fact: "Many of the machines are over 100 years old and still take quarters." },
  { name: "Castro Theatre", media: "Milk", coords: { lat: 37.7620, lng: -122.4347 }, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Castro_Theatre_San_Francisco.jpg/640px-Castro_Theatre_San_Francisco.jpg", history: "The heart of LGBTQ cinema and history in the Bay Area.", fun_fact: "It has a custom-built organ that rises out of the floor before movies." },
  { name: "Lafayette Park", media: "The Wedding Planner", coords: { lat: 37.7914, lng: -122.4277 }, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Lafayette_Park_SF.jpg/640px-Lafayette_Park_SF.jpg", history: "The scenic hilltop park where J-Lo and Matthew McConaughey meet.", fun_fact: "It’s one of the highest points in Pacific Heights, offering panoramic bay views." },
  { name: "Pier 7", media: "Ant-Man and the Wasp", coords: { lat: 37.7994, lng: -122.3970 }, image: "https://images.unsplash.com/photo-1549633041-026850c90967?auto=format&fit=crop&w=600&q=80", history: "The most scenic wooden pier on the waterfront, used for romance scenes.", fun_fact: "It is the second longest pier in SF and perfectly aligned with the Transamerica Pyramid." },
  { name: "St. Peter and Paul", media: "Sister Act", coords: { lat: 37.8016, lng: -122.4102 }, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/St._Peter_and_Paul_SF.jpg/640px-St._Peter_and_Paul_SF.jpg", history: "The North Beach church where the choir performed.", fun_fact: "Marilyn Monroe and Joe DiMaggio famously took their wedding photos on the steps." },
  { name: "Twin Peaks", media: "Memoirs of an Invisible Man", coords: { lat: 37.7544, lng: -122.4477 }, image: "https://images.unsplash.com/photo-1533512396414-7d2e05786027?auto=format&fit=crop&w=600&q=80", history: "The go-to location for city-overview car shots.", fun_fact: "Spanish settlers called them 'Los Pechos de la Chola' (The Breasts of the Indian Maiden)." },
  { name: "Cable Car Turnaround", media: "The Princess Diaries / Venom", coords: { lat: 37.7845, lng: -122.4080 }, image: "https://images.unsplash.com/photo-1563727694901-d8a436940d0f?auto=format&fit=crop&w=600&q=80", history: "The most iconic transit scene location in the world.", fun_fact: "These are the last manually operated cable cars in existence." },

  // --- CONTRA COSTA ---
  { name: "Bridges Restaurant", media: "Mrs. Doubtfire", coords: { lat: 37.8228, lng: -122.0004 }, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Bridges_Restaurant_Danville.jpg/640px-Bridges_Restaurant_Danville.jpg", history: "The site of the famous dinner and bathroom scene.", fun_fact: "You can still sit at the same table where Robin Williams sat." },
  { name: "Orinda Theatre", media: "13 Reasons Why", coords: { lat: 37.8824, lng: -122.1831 }, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Orinda_Theatre.jpg/640px-Orinda_Theatre.jpg", history: "A gorgeous 1941 movie house used as a backdrop for Netflix.", fun_fact: "The lobby features murals that are protected historic landmarks." },
  { name: "Mt. Diablo Summit", media: "Various Aerials", coords: { lat: 37.8816, lng: -121.9142 }, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Mount_Diablo_summit.jpg/640px-Mount_Diablo_summit.jpg", history: "Used for panoramic photography in many films representing Northern California.", fun_fact: "On a clear day, you can see 35 of California's 58 counties from here." },

  // --- ALAMEDA ---
  { name: "High Street Bridge", media: "The Matrix Reloaded", coords: { lat: 37.7554, lng: -122.2285 }, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/High_Street_Bridge_Alameda.jpg/640px-High_Street_Bridge_Alameda.jpg", history: "The famous highway chase was filmed on the nearby naval base.", fun_fact: "They built a 1.5-mile fake freeway specifically for the movie." },
  { name: "Jack London Square", media: "Death Valley", coords: { lat: 37.7944, lng: -122.2764 }, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Jack_London_Square_Oakland.jpg/640px-Jack_London_Square_Oakland.jpg", history: "The waterfront where many 70s grit-thrillers were filmed.", fun_fact: "Named after the author who lived in a cabin nearby." },
  { name: "UC Berkeley (Sather Gate)", media: "Oppenheimer / The Graduate", coords: { lat: 37.8721, lng: -122.2590 }, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Sather_Gate_Berkeley.jpg/640px-Sather_Gate_Berkeley.jpg", history: "Iconic campus entrance seen in 'Oppenheimer' and 'The Graduate'.", fun_fact: "The gate was the main entrance to the university until the 1920s." },
  { name: "Grand Lake Theatre", media: "Sorry to Bother You", coords: { lat: 37.8115, lng: -122.2475 }, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Grand_Lake_Theatre_Oakland.jpg/640px-Grand_Lake_Theatre_Oakland.jpg", history: "An Oakland icon used for Boots Riley's surrealist masterpiece.", fun_fact: "The marquee often features political messages to the city." },

  // --- MARIN ---
  { name: "Marin Civic Center", media: "Gattaca / Star Wars", coords: { lat: 37.9984, lng: -122.5312 }, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Marin_County_Civic_Center_Aerial.jpg/640px-Marin_County_Civic_Center_Aerial.jpg", history: "Frank Lloyd Wright's masterpiece, used as a sci-fi paradise.", fun_fact: "George Lucas used the building as inspiration for the world of Naboo." },
  { name: "Muir Woods", media: "Rise of the Planet of the Apes", coords: { lat: 37.8970, lng: -122.5811 }, image: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=600&q=80", history: "The forest where the intelligent apes find refuge.", fun_fact: "The redwoods here are some of the tallest living things on Earth." },
  { name: "Point Reyes Lighthouse", media: "The Fog (1980)", coords: { lat: 38.0037, lng: -123.0233 }, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Point_Reyes_Lighthouse_2016.jpg/640px-Point_Reyes_Lighthouse_2016.jpg", history: "The atmospheric lighthouse from the horror classic.", fun_fact: "You have to walk down 313 steps to reach the lighthouse!" },

  // --- SANTA CRUZ ---
  { name: "Beach Boardwalk", media: "The Lost Boys / Us", coords: { lat: 36.9644, lng: -122.0189 }, image: "https://images.unsplash.com/photo-1589998059171-988d887df646?auto=format&fit=crop&w=600&q=80", history: "The center of the 80s vampire cult classic 'The Lost Boys'.", fun_fact: "The Giant Dipper roller coaster is over 100 years old!" },
  { name: "Brookdale Lodge", media: "Various Noir", coords: { lat: 37.1066, lng: -122.1102 }, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Brookdale_Lodge_Dining_Room.jpg/640px-Brookdale_Lodge_Dining_Room.jpg", history: "Legendary hotel with a creek running through the dining room.", fun_fact: "Famous as a haunt for Marilyn Monroe and Dean Martin." },

  // --- SONOMA ---
  { name: "Potter Schoolhouse", media: "The Birds", coords: { lat: 38.3452, lng: -122.9739 }, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Potter_Schoolhouse_Bodega.jpg/640px-Potter_Schoolhouse_Bodega.jpg", history: "The schoolhouse where children flee the bird attack.", fun_fact: "It was a private residence when Hitchcock found it and 'aged' it." },
  { name: "Goat Rock Beach", media: "The Goonies", coords: { lat: 38.4461, lng: -123.1257 }, image: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb?auto=format&fit=crop&w=600&q=80", history: "The final scene where the pirate ship sails away.", fun_fact: "It doubled for Astoria, Oregon, due to its dramatic rock formations." },

  // --- NAPA ---
  { name: "Chateau Montelena", media: "Bottle Shock", coords: { lat: 38.5806, lng: -122.6015 }, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Chateau_Montelena.jpg/640px-Chateau_Montelena.jpg", history: "Winery that beat the French in the famous 1976 tasting.", fun_fact: "The stone castle was built in 1888 to resemble an English estate." },
  { name: "Artesa Winery", media: "Wine Country", coords: { lat: 38.2755, lng: -122.3418 }, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Artesa_Winery_Vineyard.jpg/640px-Artesa_Winery_Vineyard.jpg", history: "Used for Amy Poehler’s Netflix comedy about a girls' trip.", fun_fact: "The winery is built into a hill for natural temperature control." },

  // --- SAN LUIS OBISPO ---
  { name: "Hearst Castle", media: "Lady Gaga: G.U.Y / Spartacus", coords: { lat: 35.6852, lng: -121.1666 }, image: "https://images.unsplash.com/photo-1595123550441-d377e017de6a?auto=format&fit=crop&w=600&q=80", history: "The world-famous estate of William Randolph Hearst.", fun_fact: "The Roman Pool inside is lined with real 22-karat gold tiles." },
  { name: "Morro Rock", media: "The Lady from Shanghai", coords: { lat: 35.3711, lng: -120.8669 }, image: "https://images.unsplash.com/photo-1510134442111-e634709f3e4b?auto=format&fit=crop&w=600&q=80", history: "Orson Welles and Rita Hayworth filmed here.", fun_fact: "It is one of 'The Nine Sisters', a chain of volcanic peaks." }
];
