// RoadGuide — San Joaquin & Stanislaus Counties
// Schema matches landmarks.js exactly: name, county, emoji, lat, lon, cat, photo, fact

const LANDMARKS_VALLEY = [

// ═══════════════════════════════════════════════
// SAN JOAQUIN COUNTY
// ═══════════════════════════════════════════════

{ name:"Stockton Downtown Waterfront", county:"San Joaquin", emoji:"⚓", lat:37.9577, lon:-121.2908, cat:"Historic District", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Stockton_California_waterfront.jpg/320px-Stockton_California_waterfront.jpg", fact:"Stockton was California's <em>first inland seaport</em>, connected to San Francisco Bay by a 78-mile deep-water channel that opened in 1933 — making it the only city in the Central Valley where ocean-going ships can dock. At its Gold Rush peak, Stockton was the primary supply hub for the entire southern mines, outfitting tens of thousands of miners heading into the Sierra Nevada." },

{ name:"Haggin Museum", county:"San Joaquin", emoji:"🏛", lat:37.9674, lon:-121.2985, cat:"Museum", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Haggin_Museum_Stockton.jpg/320px-Haggin_Museum_Stockton.jpg", fact:"The Haggin Museum holds one of the most <em>surprising art collections</em> in California — a world-class assemblage of 19th-century French and American paintings acquired by Louis Haggin, a Kentucky-born millionaire who made his fortune in San Francisco banking. The collection includes works by Bouguereau, Rosa Bonheur, and Albert Bierstadt, displayed in a Beaux-Arts building in Victory Park." },

{ name:"McLeod Lake — San Joaquin County", county:"San Joaquin", emoji:"💧", lat:37.8900, lon:-121.2800, cat:"Natural Area", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Big_Break_Regional_Shoreline.jpg/320px-Big_Break_Regional_Shoreline.jpg", fact:"McLeod Lake sits at the edge of the Sacramento-San Joaquin Delta, one of the most <em>ecologically complex</em> estuaries in North America — a 1,100-mile maze of waterways where fresh Sierra snowmelt meets Pacific tidal influence. The delta's unique chemistry produces the world's most fertile peat soils, some of which have been farmed continuously for 150 years." },

{ name:"Weber Point Events Center", county:"San Joaquin", emoji:"🌳", lat:37.9573, lon:-121.2912, cat:"Historic Site", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Stockton_California_waterfront.jpg/320px-Stockton_California_waterfront.jpg", fact:"Weber Point is named for Charles Weber, who founded Stockton in <em>1849</em> and gave it its name — one of the only California cities founded by and named after a non-Spanish, non-Anglo settler. Weber, a German immigrant, acquired the land through a Mexican land grant and laid out the city grid himself, donating waterfront land specifically for public use." },

{ name:"Pixie Woods", county:"San Joaquin", emoji:"🧚", lat:37.9611, lon:-121.3122, cat:"Historic Park", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Stockton_California_waterfront.jpg/320px-Stockton_California_waterfront.jpg", fact:"Pixie Woods, opened in <em>1954</em>, is one of the last surviving storybook-theme children's parks in California — a whimsical 4-acre island of fairy-tale structures built by Stockton citizens during the postwar optimism boom. The park's tiny train, tugboat ride, and merry-go-round have operated continuously for 70 years, making it a multigenerational institution." },

{ name:"San Joaquin County Historical Museum", county:"San Joaquin", emoji:"🏚", lat:37.9897, lon:-121.2736, cat:"Museum", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Stockton_California_waterfront.jpg/320px-Stockton_California_waterfront.jpg", fact:"The San Joaquin County Historical Museum preserves the story of a county that transformed from <em>tule marsh to wheat empire to fruit paradise</em> in less than a century. Its collection includes the original equipment from the 1869 Holt Manufacturing plant in Stockton — the facility that invented the caterpillar tractor, which mechanized agriculture worldwide and later became the basis for military tank treads." },

{ name:"Holt-Atherton Special Collections — University of the Pacific", county:"San Joaquin", emoji:"📚", lat:37.9841, lon:-121.3108, cat:"Historic Site", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Stockton_California_waterfront.jpg/320px-Stockton_California_waterfront.jpg", fact:"The University of the Pacific, founded in <em>1851</em>, is the oldest chartered university in California — predating Stanford by 34 years and UC Berkeley by 18. Its historic campus along the Calaveras River houses the John Muir Papers, the most complete archive of writings by the father of American conservation, who was a close friend of UOP's early faculty." },

{ name:"Caterpillar Tractor Company Historic Site", county:"San Joaquin", emoji:"🚜", lat:37.9577, lon:-121.2908, cat:"Industrial Historic", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Stockton_California_waterfront.jpg/320px-Stockton_California_waterfront.jpg", fact:"Benjamin Holt invented the <em>caterpillar track system</em> here in Stockton in 1904, testing his first continuous-track tractor on the soft peat soils of the San Joaquin Delta where wheeled machines sank and failed. A British officer who saw the machine crawling across the field said it moved like a caterpillar — the name stuck, and the technology later became the foundation for every military tank built in World War I and II." },

{ name:"Stockton Arena", county:"San Joaquin", emoji:"🏟", lat:37.9530, lon:-121.2863, cat:"Venue", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Stockton_California_waterfront.jpg/320px-Stockton_California_waterfront.jpg", fact:"Stockton Arena anchors the <em>waterfront redevelopment</em> that transformed the city's historic port district from industrial wasteland to entertainment hub in the 2000s. The arena sits on land that was once active dry-dock facilities for the river boats that connected Stockton to San Francisco before the railroads — boats that carried the gold that built California." },

{ name:"Oak Grove Regional Park", county:"San Joaquin", emoji:"🌳", lat:37.9917, lon:-121.3389, cat:"Regional Park", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Coyote_Hills_Regional_Park.jpg/320px-Coyote_Hills_Regional_Park.jpg", fact:"Oak Grove Regional Park preserves one of the largest remaining <em>valley oak woodlands</em> in the Central Valley floor — a habitat that once covered millions of acres but has been reduced to scattered fragments by agriculture. The park's 180-acre lake draws migrating waterfowl in spectacular numbers each November, when the entire surface can be covered with thousands of ducks and geese." },

{ name:"Lodi Wine Country", county:"San Joaquin", emoji:"🍷", lat:38.1302, lon:-121.2724, cat:"Wine Region", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Altamont_Pass_Wind_Farm.jpg/320px-Altamont_Pass_Wind_Farm.jpg", fact:"Lodi is home to the largest concentration of <em>old-vine Zinfandel</em> in the world — gnarled head-trained vines planted between 1880 and 1920 that survived Prohibition because they produced table grapes. The sandy loam soils of the Mokelumne River basin, combined with cooling afternoon winds off the Sacramento Delta, produce Zinfandels of remarkable intensity that wine critics consistently rank among California's finest." },

{ name:"Lodi Lake Park", county:"San Joaquin", emoji:"💧", lat:38.1313, lon:-121.2908, cat:"Regional Park", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Coyote_Hills_Regional_Park.jpg/320px-Coyote_Hills_Regional_Park.jpg", fact:"Lodi Lake preserves a <em>riparian forest of valley oaks and cottonwoods</em> along the Mokelumne River that is among the finest urban wildlife corridors in the Central Valley. The park's nature area has documented over 200 bird species including the endangered Swainson's hawk, which nests in the tall oaks and hunts the surrounding agricultural fields during summer." },

{ name:"Micke Grove Regional Park", county:"San Joaquin", emoji:"🌿", lat:38.0547, lon:-121.3078, cat:"Regional Park", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Coyote_Hills_Regional_Park.jpg/320px-Coyote_Hills_Regional_Park.jpg", fact:"Micke Grove shelters an extraordinary <em>44-acre valley oak woodland</em> that was old-growth forest when the Spanish first arrived in California — some trees predate Columbus. The grove was donated to San Joaquin County in 1938 by William Micke, a German immigrant farmer who specifically instructed that the ancient oaks never be cut down, preserving a landscape unchanged since the Yokuts people lived beneath these trees." },

{ name:"San Joaquin Delta", county:"San Joaquin", emoji:"🌊", lat:38.0500, lon:-121.5000, cat:"Natural Area", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Big_Break_Regional_Shoreline.jpg/320px-Big_Break_Regional_Shoreline.jpg", fact:"The Sacramento-San Joaquin Delta is California's <em>most critical water infrastructure</em> — 700 miles of waterways and 57 islands that serve as the hub through which two-thirds of the state's water supply passes on its way to farms and cities. The delta's 400,000 acres of farmland sit below sea level on peat islands, protected by 1,100 miles of earthen levees that are at constant risk of collapse from earthquakes or floods." },

{ name:"Woodbridge Ecological Reserve", county:"San Joaquin", emoji:"🦅", lat:38.1667, lon:-121.3167, cat:"Wildlife Reserve", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Don_Edwards_NWR.jpg/320px-Don_Edwards_NWR.jpg", fact:"Woodbridge Ecological Reserve hosts the largest known <em>winter concentration of Sandhill Cranes</em> in California — up to 30,000 birds roost here on winter evenings, arriving in long V-formations at sunset in one of the most spectacular wildlife displays in the state. The reserve's flooded rice fields mimic the natural tule marshes that once covered the Central Valley floor." },

{ name:"Locke Historic District", county:"Sacramento", emoji:"🏘", lat:38.2472, lon:-121.5122, cat:"Historic District", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Big_Break_Regional_Shoreline.jpg/320px-Big_Break_Regional_Shoreline.jpg", fact:"Locke is the <em>only rural town in the United States built and owned entirely by Chinese immigrants</em> — established in 1915 after a fire destroyed the Chinese quarter of nearby Walnut Grove. The town's wooden false-front buildings, Chinese stores, and gambling halls survive almost completely intact, recognized as a National Historic Landmark and one of the most atmospheric Gold Rush-era townscapes remaining in California." },

{ name:"Isleton Historic District", county:"Sacramento", emoji:"🏚", lat:38.1597, lon:-121.6119, cat:"Historic District", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Big_Break_Regional_Shoreline.jpg/320px-Big_Break_Regional_Shoreline.jpg", fact:"Isleton was the <em>asparagus capital of the world</em> in the early 20th century — Chinese and Japanese workers developed sophisticated techniques for growing and canning asparagus in the Delta's peat soils, shipping millions of cans annually to markets across America and Europe. The town's canneries are silent now, but its preserved Chinatown block and main street remain largely unchanged from the 1920s." },

{ name:"Calaveras River Parkway", county:"San Joaquin", emoji:"🌿", lat:37.9700, lon:-121.3100, cat:"Trail", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Sunol_Regional_Wilderness.jpg/320px-Sunol_Regional_Wilderness.jpg", fact:"The Calaveras River gives its name — Spanish for <em>'skulls'</em> — from a gruesome discovery made by the Gabriel Moraga expedition in 1806, which found a large cache of Native American skulls along its banks, evidence of a deadly epidemic that had swept through Yokuts villages. The river's 15-mile parkway trail now winds through cottonwood forest past the sites of early Stockton's founding farms." },

{ name:"Stockton Film Location — Downtown Streets", county:"San Joaquin", emoji:"🎬", lat:37.9577, lon:-121.2908, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Stockton_California_waterfront.jpg/320px-Stockton_California_waterfront.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>Grease (1978) / various productions</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>Stockton's downtown streets and surrounding areas have served as stand-ins for 1950s American towns in numerous productions, most notably Grease, which used the region's classic American streetscapes for several sequences.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>The Central Valley's flat terrain, wide streets, and preserved mid-century architecture make it a favorite double for generic American settings in Hollywood productions.</span></div>" },

{ name:"Pixie Woods — Stockton Film Location", county:"San Joaquin", emoji:"🎬", lat:37.9611, lon:-121.3122, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Stockton_California_waterfront.jpg/320px-Stockton_California_waterfront.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>Various TV Productions</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>Pixie Woods' enchanting storybook structures and vintage carnival rides have been used as nostalgic Americana backdrops in television commercials and independent productions seeking authentic mid-century charm.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>Pixie Woods is one of fewer than a dozen storybook children's parks still operating in the United States — most were demolished in the 1970s and 1980s as tastes changed.</span></div>" },

{ name:"Mormon Slough Wetlands", county:"San Joaquin", emoji:"🦆", lat:37.9800, lon:-121.2600, cat:"Natural Area", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Big_Break_Regional_Shoreline.jpg/320px-Big_Break_Regional_Shoreline.jpg", fact:"Mormon Slough preserves a fragment of the <em>vast tule marsh ecosystem</em> that once covered over a million acres of the Central Valley before agricultural drainage destroyed most of it in the 19th century. The slough takes its name from Mormon emigrants who camped along its banks in 1846 while scouting routes to California — arriving just months before the Gold Rush transformed everything." },

{ name:"San Joaquin River National Wildlife Refuge", county:"San Joaquin", emoji:"🦢", lat:37.7833, lon:-121.1667, cat:"Wildlife Refuge", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Don_Edwards_NWR.jpg/320px-Don_Edwards_NWR.jpg", fact:"The San Joaquin River refuge protects critical habitat for the <em>Giant Garter Snake</em> — the largest native snake in California, found almost nowhere else on Earth — which depends on the network of rice fields and sloughs that replaced the valley's original tule marshes. The refuge's seasonal wetlands also support over 200 bird species and the largest remaining run of Chinook salmon in the Central Valley." },

{ name:"Lodi Arch — Historic Gateway", county:"San Joaquin", emoji:"🏛", lat:38.1302, lon:-121.2724, cat:"Historic Site", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Altamont_Pass_Wind_Farm.jpg/320px-Altamont_Pass_Wind_Farm.jpg", fact:"The Lodi Arch, erected in <em>1907</</em> over Sacramento Street, became one of the most photographed landmarks in the Central Valley — a triumphal gateway celebrating Lodi's emergence as the tokay grape capital of America. The arch's restoration in the 1990s anchored a downtown revival that transformed Lodi from a fading farm town to a destination wine region visited by over a million people annually." },

{ name:"Thornton Road Vineyards", county:"San Joaquin", emoji:"🍇", lat:38.2200, lon:-121.4200, cat:"Wine Region", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Altamont_Pass_Wind_Farm.jpg/320px-Altamont_Pass_Wind_Farm.jpg", fact:"The Thornton Road corridor contains some of California's oldest <em>planted Zinfandel and Flame Tokay vines</em>, with several blocks dating to the 1880s — making them among the oldest continuously producing wine vines in North America. The sandy soils here are naturally low in phylloxera, the root louse that devastated European vineyards in the 1870s, which is why so many vines survived ungrafted for over a century." },

{ name:"Bear Creek Bikeway", county:"San Joaquin", emoji:"🚴", lat:38.1100, lon:-121.2900, cat:"Trail", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Sunol_Regional_Wilderness.jpg/320px-Sunol_Regional_Wilderness.jpg", fact:"The Bear Creek Bikeway winds through the agricultural heart of San Joaquin County past <em>historic farmsteads, orchards, and vineyards</em> that have been in continuous production since the 1880s. The trail follows the original wagon road that connected Lodi's grape ranches to the Stockton waterfront — the route along which millions of boxes of tokay grapes were hauled to river boats and shipped to San Francisco markets." },

{ name:"Camanche Reservoir", county:"San Joaquin", emoji:"💧", lat:38.2333, lon:-120.9667, cat:"Reservoir", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Los_Vaqueros_Reservoir.jpg/320px-Los_Vaqueros_Reservoir.jpg", fact:"Camanche Reservoir, completed in <em>1964</em>, flooded the original town of Camanche — a Gold Rush settlement that sat at the confluence of the Mokelumne River's north and south forks. At low water years, the rooflines of submerged buildings have occasionally surfaced above the waterline, ghostly reminders of the community of 1,500 people that was relocated to build the dam." },

// ═══════════════════════════════════════════════
// STANISLAUS COUNTY
// ═══════════════════════════════════════════════

{ name:"Modesto Arch", county:"Stanislaus", emoji:"🏛", lat:37.6391, lon:-120.9969, cat:"Historic Landmark", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Modesto_Arch.jpg/320px-Modesto_Arch.jpg", fact:"The Modesto Arch, erected in <em>1912</em> and bearing the motto 'Water, Wealth, Contentment, Health,' is one of California's most recognized civic landmarks — a testament to the irrigation systems that transformed the Stanislaus County grasslands into the most productive agricultural region on Earth. The arch's motto was chosen by popular vote and perfectly encapsulates the Central Valley's identity as a place built entirely on the controlled distribution of water." },

{ name:"McHenry Mansion", county:"Stanislaus", emoji:"🏰", lat:37.6391, lon:-120.9969, cat:"Historic House", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Modesto_Arch.jpg/320px-Modesto_Arch.jpg", fact:"The McHenry Mansion, built in <em>1883</em> for banker Robert McHenry, is the finest surviving Victorian residence in the Central Valley — a 15-room Italianate mansion furnished with original period pieces that documents the extraordinary wealth generated by Stanislaus County's first agricultural boom. McHenry donated the land for Modesto's public library and helped fund the irrigation canals that made the surrounding farmland viable." },

{ name:"Graffiti USA Classic Car Museum", county:"Stanislaus", emoji:"🚗", lat:37.6378, lon:-120.9969, cat:"Museum", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Modesto_Arch.jpg/320px-Modesto_Arch.jpg", fact:"Modesto is the real-world inspiration for <em>American Graffiti</em> — George Lucas grew up here and based his 1973 film on cruising McHenry Avenue on Friday nights in the late 1950s. The Graffiti USA museum celebrates the car culture Lucas immortalized, displaying dozens of period vehicles alongside memorabilia from the film that launched both Lucas's career and the nostalgia wave that defined 1970s Hollywood." },

{ name:"George Lucas Hometown — Modesto", county:"Stanislaus", emoji:"🎬", lat:37.6391, lon:-120.9969, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Modesto_Arch.jpg/320px-Modesto_Arch.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>American Graffiti (1973)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>George Lucas based his breakthrough film on his own teenage years cruising McHenry Avenue in Modesto. The film was actually shot in Petaluma, but every character, car, and scene draws from Lucas's specific Modesto memories.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>American Graffiti launched the careers of Richard Dreyfuss, Harrison Ford, and Ron Howard simultaneously — and its $775,000 budget returned $200 million, funding Lucas's next project: Star Wars.</span></div>" },

{ name:"McHenry Avenue Cruise Strip", county:"Stanislaus", emoji:"🎬", lat:37.6800, lon:-120.9969, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Modesto_Arch.jpg/320px-Modesto_Arch.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>American Graffiti (1973)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>McHenry Avenue was the real Friday night cruise strip that George Lucas and his friends drove endlessly in the late 1950s — the ritual of driving loops on this stretch of road inspired the entire structure of American Graffiti.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>Every summer Modesto hosts Graffiti Summer, a weeks-long classic car celebration drawing 100,000 visitors who cruise the same streets Lucas did as a teenager.</span></div>" },

{ name:"Knights Ferry Historic Site", county:"Stanislaus", emoji:"🌉", lat:37.8256, lon:-120.6653, cat:"Historic Site", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Morgan_Territory_Regional_Preserve.jpg/320px-Morgan_Territory_Regional_Preserve.jpg", fact:"Knights Ferry's <em>covered bridge</em>, built in 1863, is the longest covered bridge west of the Mississippi River at 330 feet — spanning the Stanislaus River at the point where thousands of Gold Rush miners crossed heading into the Southern Mines. The town surrounding it was a major supply point for miners and later a milling center, and its collection of stone and brick buildings from the 1850s–1870s represents one of the most intact Gold Rush-era townscapes in the San Joaquin Valley." },

{ name:"Turlock Lake State Recreation Area", county:"Stanislaus", emoji:"💧", lat:37.5567, lon:-120.6175, cat:"State Park", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Los_Vaqueros_Reservoir.jpg/320px-Los_Vaqueros_Reservoir.jpg", fact:"Turlock Lake was created by the Tuolumne River, which carries snowmelt from <em>Yosemite National Park's high country</em> down through the foothills and into the Central Valley. The lake's clear, cold water — unusual for the hot valley floor — has made it the premier summer swimming and water sports destination in Stanislaus County for over 80 years." },

{ name:"McConnell State Recreation Area", county:"Stanislaus", emoji:"🌿", lat:37.3506, lon:-120.7358, cat:"State Park", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Sunol_Regional_Wilderness.jpg/320px-Sunol_Regional_Wilderness.jpg", fact:"McConnell preserves one of the last fragments of <em>riparian forest</em> along the Merced River — a corridor of cottonwoods, willows, and valley oaks that once lined every Central Valley river before agriculture stripped most waterways bare. The park's beach on the Merced River is one of the few places in the valley where you can swim in a free-flowing river surrounded by native vegetation." },

{ name:"Caswell Memorial State Park", county:"Stanislaus", emoji:"🌲", lat:37.6897, lon:-121.0142, cat:"State Park", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Sunol_Regional_Wilderness.jpg/320px-Sunol_Regional_Wilderness.jpg", fact:"Caswell Memorial State Park protects 258 acres of the last remaining <em>valley oak riparian forest</em> on the San Joaquin River — a forest type that once extended for hundreds of miles along the river but was almost completely eliminated by agriculture and development. The park is home to the riparian brush rabbit, a federally endangered subspecies found only in a handful of San Joaquin Valley forest fragments." },

{ name:"Stanislaus River Parks", county:"Stanislaus", emoji:"🌊", lat:37.6400, lon:-120.9400, cat:"Regional Park", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Sunol_Regional_Wilderness.jpg/320px-Sunol_Regional_Wilderness.jpg", fact:"The Stanislaus River was the site of one of California's most significant <em>environmental battles</em> — a decade-long fight in the 1970s and early 1980s to save the New Melones Canyon from flooding. The campaign, led by a young activist named Mark Dubois who chained himself to the canyon walls, became a landmark moment in the American conservation movement even though the dam was ultimately built." },

{ name:"Empire Mine — Oakdale", county:"Stanislaus", emoji:"⛏", lat:37.7761, lon:-120.8461, cat:"Historic Site", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Morgan_Territory_Regional_Preserve.jpg/320px-Morgan_Territory_Regional_Preserve.jpg", fact:"The foothills above Oakdale were some of the richest placer gold deposits in the Southern Mines — the <em>Stanislaus River canyon</em> yielded millions of dollars in gold to Mexican, Chilean, and American miners who worked its gravel bars beginning in 1848. The town of Sonora, just above the county line, was the wealthiest per capita city in California during the early Gold Rush, funded almost entirely by gold from rivers draining through Stanislaus County." },

{ name:"Modesto Reservoir", county:"Stanislaus", emoji:"💧", lat:37.6167, lon:-120.8333, cat:"Reservoir", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Los_Vaqueros_Reservoir.jpg/320px-Los_Vaqueros_Reservoir.jpg", fact:"Modesto Reservoir is a <em>critical link in the Modesto Irrigation District</em> — one of the oldest irrigation districts in California, organized in 1887 when valley farmers realized that without organized water delivery their crops would fail every dry year. The MID's canal system transformed 55,000 acres of dry grassland into some of the most productive farmland in the world, growing almonds, walnuts, peaches, and wine grapes." },

{ name:"Turlock Historic Downtown", county:"Stanislaus", emoji:"🏘", lat:37.4947, lon:-120.8464, cat:"Historic District", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Modesto_Arch.jpg/320px-Modesto_Arch.jpg", fact:"Turlock was founded by Swedish immigrants in the <em>1870s</em> and retains a distinctly Scandinavian agricultural heritage visible in its church architecture, cooperative farming traditions, and annual Swedish festival. The town's downtown commercial district, built between 1900 and 1930, is one of the best-preserved early 20th-century commercial streetscapes in the Central Valley." },

{ name:"Oakdale Cowboy Museum", county:"Stanislaus", emoji:"🤠", lat:37.7761, lon:-120.8461, cat:"Museum", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Morgan_Territory_Regional_Preserve.jpg/320px-Morgan_Territory_Regional_Preserve.jpg", fact:"Oakdale bills itself as the <em>Cowboy Capital of the World</em> — a title with genuine historical basis, as the town was the center of the vast Miller and Lux cattle operation that ran over a million acres of California rangeland in the late 19th century. The Cowboy Museum preserves the equipment, photographs, and stories of the vaquero tradition that shaped Central Valley ranching culture from the Spanish era through the 20th century." },

{ name:"Riverbank Historic District", county:"Stanislaus", emoji:"🏚", lat:37.7272, lon:-120.9353, cat:"Historic District", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Modesto_Arch.jpg/320px-Modesto_Arch.jpg", fact:"Riverbank's historic district preserves the commercial core of a <em>Portuguese immigrant community</em> that established some of the most successful dairy farms in California's history — a tradition so strong that California's dairy industry still has deep Portuguese roots traceable directly to the families who came to Stanislaus County from the Azores in the early 20th century. The community's Holy Ghost festivals have been celebrated here continuously since 1915." },

{ name:"Don Pedro Reservoir", county:"Tuolumne", emoji:"💧", lat:37.7119, lon:-120.4022, cat:"Reservoir", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Los_Vaqueros_Reservoir.jpg/320px-Los_Vaqueros_Reservoir.jpg", fact:"Don Pedro Reservoir, impounded by the <em>second-tallest dam in California</em>, holds more water than San Francisco Bay at high tide — 2.03 million acre-feet that supplies drinking water to 2.6 million people in the Bay Area. The reservoir's clear blue waters and 160 miles of shoreline make it the most visited recreation area in the Sierra Nevada foothills, drawing over a million visitors annually." },

{ name:"Jacob Myers Park — Stanislaus River", county:"Stanislaus", emoji:"🌿", lat:37.6350, lon:-120.9900, cat:"Regional Park", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Sunol_Regional_Wilderness.jpg/320px-Sunol_Regional_Wilderness.jpg", fact:"Jacob Myers Park sits on the <em>last free-flowing reach</em> of the Stanislaus River before it joins the San Joaquin — one of the few stretches of the lower Stanislaus that retains native riparian vegetation and seasonal salmon habitat. The park's cottonwood and willow forest provides critical nesting habitat for the yellow warbler and other songbirds that have disappeared from most of the intensively farmed valley floor." },

{ name:"Tulloch Reservoir", county:"Calaveras", emoji:"💧", lat:37.8308, lon:-120.5947, cat:"Reservoir", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Los_Vaqueros_Reservoir.jpg/320px-Los_Vaqueros_Reservoir.jpg", fact:"Tulloch Reservoir sits at the confluence of three Gold Rush rivers in the heart of the Mother Lode — the Stanislaus, its north fork, and several gold-bearing tributaries that once made this one of the richest placer mining regions in California. The reservoir's warm, clear water and sheltered coves have made it a favorite of houseboaters who spend weeks exploring the flooded canyon landscape." },

{ name:"Hetch Hetchy Aqueduct — Valley Terminus", county:"Stanislaus", emoji:"🔧", lat:37.5500, lon:-121.0000, cat:"Historic Infrastructure", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Sunol_Regional_Wilderness.jpg/320px-Sunol_Regional_Wilderness.jpg", fact:"The Hetch Hetchy Aqueduct, which carries <em>Yosemite's water</em> 167 miles to San Francisco, passes directly through Stanislaus County on its gravity-fed journey across the Central Valley. Built between 1914 and 1934, the aqueduct is one of the greatest engineering achievements in California history — and one of the most controversial, as it required the damming of Hetch Hetchy Valley, which John Muir considered more beautiful than Yosemite itself." },

{ name:"Stanislaus National Forest Boundary", county:"Stanislaus", emoji:"🌲", lat:37.8500, lon:-120.5000, cat:"Natural Area", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Morgan_Territory_Regional_Preserve.jpg/320px-Morgan_Territory_Regional_Preserve.jpg", fact:"The Stanislaus National Forest begins where the county's foothill oak woodlands give way to <em>ponderosa pine and mixed conifer forest</em> — a transition zone that concentrates remarkable biodiversity where species from the valley, foothills, and mountains overlap. The forest covers 898,000 acres of the Sierra Nevada's west slope and contains more miles of wild and scenic river than any national forest in California." },

{ name:"Waterford Historic Bridge", county:"Stanislaus", emoji:"🌉", lat:37.6425, lon:-120.7597, cat:"Historic Site", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Morgan_Territory_Regional_Preserve.jpg/320px-Morgan_Territory_Regional_Preserve.jpg", fact:"The Waterford Bridge over the Tuolumne River, built in <em>1916</em>, is one of the last remaining early automobile bridges in the Central Valley — a concrete arch structure that replaced the ferry crossing used by Gold Rush travelers. The bridge's approach roads follow the original Sonora Road that carried miners from Stockton to the Southern Mines, making this crossing one of the most historically significant river crossings in California's gold country history." },

{ name:"Salida Diner — American Graffiti Location", county:"Stanislaus", emoji:"🎬", lat:37.6667, lon:-121.0833, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Modesto_Arch.jpg/320px-Modesto_Arch.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>American Graffiti (1973)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>The roadside diners and drive-ins of the Modesto-Salida corridor were the direct inspiration for Mel's Drive-In in American Graffiti — George Lucas spent countless teenage hours at establishments exactly like these along the cruise route.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>The actual Mel's Drive-In used in filming was in San Francisco, but its aesthetic was modeled precisely on the Modesto drive-ins Lucas grew up with — right down to the carhops and neon signs.</span></div>" },

{ name:"Turlock Lake Film Location", county:"Stanislaus", emoji:"🎬", lat:37.5567, lon:-120.6175, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Los_Vaqueros_Reservoir.jpg/320px-Los_Vaqueros_Reservoir.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>Various California Productions</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>Turlock Lake's blue waters set against the golden California hills have doubled for generic 'California summer lake' settings in numerous TV commercials and independent productions seeking an affordable Central Valley filming location.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>The Central Valley's 300 days of sunshine and minimal fog make it one of the most reliably filmable regions in California — a key reason George Lucas chose to base his production company near the area he grew up.</span></div>" },

{ name:"Knights Ferry — Film Location", county:"Stanislaus", emoji:"🎬", lat:37.8256, lon:-120.6653, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Morgan_Territory_Regional_Preserve.jpg/320px-Morgan_Territory_Regional_Preserve.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>Various Westerns and Period Productions</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>Knights Ferry's covered bridge, 19th-century stone buildings, and wild river setting make it one of the most authentic Gold Rush-era film locations in California, used repeatedly for westerns and period dramas requiring a convincing 1860s American West backdrop.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>The covered bridge was designed by a West Point-trained engineer and built using techniques identical to New England covered bridges — making it visually unique in the California landscape.</span></div>" }

];
